var covers =[
      {"key":"B016F3M7OM","category":"BodyCover",
      "name":"AERO Car Cover | KIA Carens (2022) - Triple-Stitched Waterproof and Heat Resistant with Mirror and Antenna Pockets (Silver)",
      "price":50,
      "stock":"48","img":"https://i.ibb.co/ystp7Vm/cover9.jpg",
      "features":"100% Waterproof, Dustproof and Heat-Resistant covers that give your car a 360-degree protection Keeps your car dry and protected from Bird Droppings and Acid Rain",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},{"key":"B01MQ0FSS0","category":"BodyCover",
"name":"ACHO Car Cover | Audi Q8 (2020) - Triple-Stitched Waterproof and Heat Resistant with Mirror Pockets (Red)",
"price":70,
"stock":"48","img":"https://i.ibb.co/fGZ5SYD/cover8.jpg",
"features":"100% Waterproof, Dustproof and Heat-Resistant covers that give your car a 360-degree protection Keeps your car dry and protected from Bird Droppings and Acid Rain",
"productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."},
{"key":"B01KVIN26O","category":"BodyCover",
      "name":"AERO Car Cover | KIA Carens (2022) - Triple-Stitched Waterproof and Heat Resistant with Mirror and Antenna Pockets (Silver)",
      "price":80,
      "stock":"48","img":"https://i.ibb.co/FwKH3kd/cover7.jpg",
      "features":"100% Waterproof, Dustproof and Heat-Resistant covers that give your car a 360-degree protection Keeps your car dry and protected from Bird Droppings and Acid Rain",
      "productDetails":"This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years. The car body covers designed by AutoFurnish offer a snug fit without leaving any gaps. Each body cover is custom designed as per the vehicle’s specification in order to give the best fitting."},
{"key":"B00W68DSWQ","category":"BodyCover",
      "name":"ACHO Car Cover | KIA Carens (2021) - Triple-Stitched Waterproof and Heat Resistant with Mirror Pockets (Blue)",
      "price":40,
      "stock":"45","img":"https://i.ibb.co/fGZ5SYD/cover8.jpg",
      "features":"100% Waterproof, Dustproof and Heat-Resistant covers that give your car a 360-degree protection Keeps your car dry and protected from Bird Droppings and Acid Rain",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},   
{"key":"B01N6E66RN","category":"BodyCover",
      "name":"AERO Car Cover | KIA Carens (2022) - Triple-Stitched Waterproof and Heat Resistant with Mirror and Antenna Pockets (Silver)",
      "price":50,
      "stock":"48","img":"https://i.ibb.co/8chjBD6/cover6.jpg",
      "features":"100% Waterproof, Dustproof and Heat-Resistant covers that give your car a 360-degree protection Keeps your car dry and protected from Bird Droppings and Acid Rain",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},
{"key":"B01CG62D00","category":"BodyCover",
      "name":"ARC AQUA Car Cover | KIA Carens (2022) - Triple-Stitched Water Resistant and Heat Resistant with Mirror Pockets",
      "price":65,
      "stock":"22","img":"https://i.ibb.co/kBwVdSW/cover5.jpg",
      "features":"Made from High-Quality Taffeta fabric with a highly reflective outer layer that repels harmful UV rays, preserves the paint and prevents Over-Heating",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},
{"key":"B01LWPSB57","category":"BodyCover",
      "name":"ARC AQUA Car Cover | KIA Carens (2022) - Triple-Stitched Water Resistant and Heat Resistant with Mirror Pockets",
      "price":65,
      "stock":"22","img":"https://i.ibb.co/dM34vr1/cover4.jpg",
      "features":"Made from High-Quality Taffeta fabric with a highly reflective outer layer that repels harmful UV rays, preserves the paint and prevents Over-Heating",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},

{"key":"B01N0XDRYO","category":"BodyCover",
      "name":"ARC AQUA Car Cover | KIA Carens (2020) - Triple-Stitched Water Resistant and Heat Resistant with Mirror Pockets",
      "price":63,
      "stock":"15","img":"https://i.ibb.co/0jT9hhS/cover3.jpg",
      "features":"Made from High-Quality Taffeta fabric with a highly reflective outer layer that repels harmful UV rays, preserves the paint and prevents Over-Heating",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},
{"key":"B01MRWZ4KL","category":"BodyCover",
      "name":"ARC AQUA Car Cover | Tata Punch (2021) - Triple-Stitched Water Resistant and Heat Resistant with Mirror Pockets",
      "price":63,
      "stock":"15","img":"https://i.ibb.co/DbsQRw4/cover2.jpg",
      "features":"Made from High-Quality Taffeta fabric with a highly reflective outer layer that repels harmful UV rays, preserves the paint and prevents Over-Heating",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},
{"key":"B006J0SVWE","category":"BodyCover",
      "name":"ARC AQUA Car Cover | Tata Punch (2021) - Triple-Stitched Water Resistant and Heat Resistant with Mirror Pockets",
      "price":63,
      "stock":"15","img":"https://i.ibb.co/92d20jR/cover1.jpg",
      "features":"Made from High-Quality Taffeta fabric with a highly reflective outer layer that repels harmful UV rays, preserves the paint and prevents Over-Heating",
      "productDetails":"Our AERO series car body cover has a separate antenna pocket to ensure that your car's antenna does not bend or break. This extra pocket keeps your antenna safe and protected from all kinds of damages. This car body cover protects your car’s exterior as well as interior from excessive heat and keeps your car cool in the summers. Ultimate Durable UV/sun protection to protect your interior and paint. This waterproof car cover will keep your car paint protected from heavy rainfall. The waterproof and dustproof material protects your vehicle against wet, dusty and humid climatic conditions. Stitching plays a vital role in keeping the fabric intact, sturdy and sustainable. Our superior triple stitching technology ensures that the cover retains its fitting, design and aesthetics for many years."
},
]
export default covers;